#!/bin/sh
#

shellcheck gitguild
if [ $? != 0 ]; then
  exit 1
fi
shellcheck configure
if [ $? != 0 ]; then
  exit 1
fi
shellcheck t/*.sh
if [ $? != 0 ]; then
  exit 1
fi
make test
if [ $? != 0 ]; then
  exit 1
fi

